[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

# Basic info about your module
[project]
# update with your module name. This will typiclaly be the name of the module folder within the src directory
name = "your_module"
version = "0.0.1"
authors = [{ name = "Your Name", email = "you@your_website.com" }]
description = "A short descripton of your module"
# update with your license type
license = "MIT" 

# NOTE: PyAres requires Python 3.10 or newer, but other your logic may have other version requirements
requires-python = ">= 3.10"

# Add the packages that your module requires. PyAres is a defualt requirement. 
# Specific versions of packages can also be specified as needed. 
# NOTE: Numpy is included only as an example.
dependencies = [
  "PyAres>=1.0.0b1",
  "numpy>=2.2.0", 
]

# Links to project websites if relavant
[project.urls]
"Homepage" = "your_website.com"
