#!/usr/bin/env python3
# -*- coding:utf-8 -*-

"""
This planner implements a Global Gaussian Process Regression (GPR) strategy. 
It uses historical data to build a surrogate model of the experimental space and
suggests new points by maximizing an Upper Confidence Bound (UCB) acquisition function.

There are a few settings that can be adjusted to achieve faster or better optimization
depending on your parameter space.

Number of Candidates: This is a value that determines how many "fake" experimental canditates there will be. This number is further
broken down into Local And Global Canditates. These local candidates are potential inputs generated by giving a small random perturbation to "best" 
previously found input value. The Global case is a completely random point generation outside of the predefined local region that encourages exploration,
and prevents the case of local maxima disguised as absolute maxima.

Exploration Strength: A direct factor that impacts the UCB by increasing the weight of more explorative points compared to ones more similar to past inputs.

Scale Multiplier: A adjustable factor that can be used to modify the input variations affect on the noise scale, this noise scale is the local region used
when generating our local candidates.
"""

# -----------------------------------------------------------------------------
# 1. Import Necessary Modules
# -----------------------------------------------------------------------------
import numpy as np
import traceback
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import Matern
from scipy.spatial.distance import pdist
from PyAres import AresPlannerService, PlanRequest, PlanResponse, AresDataType, Outcome

# -----------------------------------------------------------------------------
# 2. Define Your Service Details 
# -----------------------------------------------------------------------------
name = "GPR_Global_Planner"
description = "Suggests new points by maximizing a UCB acquisition function on a GPR surrogate model."
version = "1.0.0"
port = 7307 
local = True

# ----------------------------------------------------------------------------- 
# 3. Define the Planning Logic
# -----------------------------------------------------------------------------
def normalize(value, min_val, max_val):
	"""Scales physical values to [0, 1] for improved numerical stability in GPR."""
	if (max_val - min_val) == 0:
		return 0.5
	return (value - min_val) / (max_val - min_val)

def denormalize(norm_value, min_val, max_val):
	"""Converts normalized unit-space back into physical parameter units."""
	return norm_value * (max_val - min_val) + min_val

def planner(request: PlanRequest) -> PlanResponse:
	"""
	Main planning function to suggest next experimental values.
	"""
	print("--- GPR Global Planner started ---")
	param_names, param_vals, all_values_matrix = [], [], []
	maximums, minimums = [], []
	
	try:
		# --- 1. HYPERPARAMETER INITIALIZATION ---
		settings = request.settings
		num_candidates = int(settings.get("Number of Candidates"))
		exploration_strength = float(settings.get("Exploration Strength"))
		scale_multiplier = float(settings.get("Scale Multiplier"))
		print(exploration_strength)
		seed_setting = settings.get('Seed')
		seed = int(seed_setting) if seed_setting else None
		rng = np.random.default_rng(seed=seed)
		
		# --- 2. DATA EXTRACTION & NORMALIZATION (Updated Plumbing) ---
		past_values = request.analysis_results
		
		for param in request.parameters:
			if not param.is_planned:
				continue
			
			maximums.append(param.maximum_value)
			minimums.append(param.minimum_value)
			param_names.append(param.name)
			
			planned_history = [v.planned_value for v in param.param_history]
			
			# Normalize history to ensure the kernel length-scales are meaningful
			if len(planned_history) != 0:
				values = [normalize(v, param.minimum_value, param.maximum_value) for v in planned_history]
			else:
				# If no history, generate a random normalized value for the initial state
				values = [normalize(rng.uniform(param.minimum_value, param.maximum_value), param.minimum_value, param.maximum_value)]
			
			all_values_matrix.append(values)
			
		# Format inputs into an (N_samples, N_features) matrix
		past_inputs = np.vstack(all_values_matrix).T
		
		# Handle empty results (e.g. on the very first run)
		if len(past_values) == 0:
			past_values = [50]
		past_values = np.array(past_values)
		# --- 3. SURROGATE MODELING ---
		kernel = Matern(length_scale=1.0, length_scale_bounds="fixed")
		gp = GaussianProcessRegressor(kernel=kernel, alpha=1e-4)
		gp.fit(past_inputs, past_values)

		# --- 4. CONVERGENCE ESTIMATION ---
		top_k = min(5, len(past_inputs))
		top_indices = np.argsort(past_values)[-top_k:]
		top_inputs = past_inputs[top_indices]
		input_variation = np.mean(pdist(top_inputs)) if len(top_inputs) > 1 else 1.0

		# --- 5. HYBRID CANDIDATE GENERATION ---
		noise_scale = np.clip(input_variation * scale_multiplier, 0.001, 0.2)
		local_factor = np.clip(input_variation / 1.2, 0.1, .8)
		dim = past_inputs.shape[1]
		
		num_local = int(local_factor * num_candidates)
		num_global = num_candidates - num_local
		best_input = past_inputs[np.argmax(past_values)]
		
		local_candidates = best_input + rng.normal(scale=noise_scale, size=(num_local, dim))
		global_candidates = rng.random(size=(num_global, dim))
		
		candidates = np.vstack([np.clip(local_candidates, 0, 1), global_candidates])

		# --- 6. ACQUISITION FUNCTION (UCB) ---
		mean, std = gp.predict(candidates, return_std=True)
		std = np.maximum(std, 0.05)
		exploration_boost = np.clip(exploration_strength * (1.0 - input_variation), 0.0, exploration_strength)
		scaled_kappa = (exploration_strength + exploration_boost) * std
		acquisition_scores = mean + scaled_kappa
		next_input = candidates[np.argmax(acquisition_scores)]
		# --- 7. FINAL DENORMALIZATION & RESPONSE ---
		final_param_vals = []
		for i in range(len(param_names)):
			phys_val = denormalize(next_input[i], minimums[i], maximums[i])
			final_param_vals.append(np.clip(phys_val, minimums[i], maximums[i]))
		response = PlanResponse(parameter_names=param_names, parameter_values=final_param_vals, outcome=Outcome.SUCCESS)

	except Exception as e:
		print("\n--- GPR PLANNER CRASHED ---")
		traceback.print_exc()
		print("---------------------------\n")
		# Fallback to extract names safely if a crash happened before they were built
		p_names = [p.name for p in getattr(request, 'parameters', [])] if not param_names else param_names
		response = PlanResponse(parameter_names=p_names, parameter_values=[-1]*len(p_names), outcome=Outcome.FAILURE, message=str(e))
	return response

# -----------------------------------------------------------------------------
# 8. Configure and Start Planner Service.
# -----------------------------------------------------------------------------
if __name__ == "__main__":
	planner_service = AresPlannerService(planner, name, version, description, use_localhost=local, port=port)
	planner_service.add_supported_type(AresDataType.NUMBER)

	# Define the settings that can be configured in ARES OS
	planner_service.add_setting("Number of Candidates", AresDataType.NUMBER, default_value=200) 
	planner_service.add_setting("Exploration Strength", AresDataType.NUMBER, default_value=20.0)
	planner_service.add_setting("Scale Multiplier", AresDataType.NUMBER, default_value=0.5)
	planner_service.add_setting("Seed", AresDataType.NUMBER, default_value=None) 

	try:
		planner_service.start()
	except Exception as e:
		print(f"An Exception Occurred while starting service: {e}")
	except KeyboardInterrupt:
		print(f"\nShutting Down PyAres Service...")
